<a href="https://colab.research.google.com/github/shoma1001/Summer_Training_2026_NIT_Patna/blob/main/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
#assigning column names to the dataset
names=['sepal-length','sepal-width','petal-length','petal-width','Class']
#read the dataset
dataset = pd.read_csv(url,names=names)

In [ ]:
dataset.head()

,sepal-length,sepal-width,petal-length,petal-width,Class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [ ]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,4].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=7)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.90      0.90      0.90        10
 Iris-virginica       0.89      0.89      0.89         9

       accuracy                           0.93        30
      macro avg       0.93      0.93      0.93        30
   weighted avg       0.93      0.93      0.93        30

[[11  0  0]
 [ 0  9  1]
 [ 0  1  8]]


In [ ]:
#finding accuracy from confusion matrix
a= cm.shape
correct_prediction=0
false_prediction=0

for i in range(a[0]):
  for j in range(a[1]):
    if i==j:
      correct_prediction=correct_prediction+cm[i,j]
    else:
      false_prediction=false_prediction+cm[i,j]
print('Correct Prediction:', correct_prediction)
print('False Prediction:', false_prediction)
print('\n\nAccuracy of the KNN algorithm is:',correct_prediction/(cm.sum()))

Correct Prediction: 28
False Prediction: 2


Accuracy of the KNN algorithm is: 0.9333333333333333
